name: Deploy Docker Container to EC2

on:
  release:
    types: [created]

jobs:
  deploy:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Configure AWS credentials
        uses: aws-actions/configure-aws-credentials@v1
        with:
          aws-access-key-id: ${{ secrets.AWS_ACCESS_KEY_ID }}
          aws-secret-access-key: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
          aws-region: us-west-2

      - name: Build and push Docker image
        uses: docker/build-push-action@v2
        with:
          context: .
          push: true
          tags: objectstrajectories:${{ github.sha }}

      - name: Deploy Docker container to EC2
        uses: aws-actions/aws-cli@v1
        with:
          args: |
            s3 cp s3://your-s3-bucket/objectstrajectories:${{ github.sha }} /tmp/image.tar.gz
            docker load -i /tmp/image.tar.gz
            docker run -d --name object-trajectories -p 80:80 objectstrajectories:${{ github.sha }}
